messages:
  PREFIX:
  CREATE_GROUP_USAGE: "Usage: /group create <rank> <displayname>"
  LIST_GROUP_USAGE: "Usage/group list"
  DELETE_GROUP_USAGE: "Usage: /group delete <rank>"
  GROUP_INFO_USAGE: "Usage: /group info <player>"
  GROUP_GIVE_USAGE: "Usage: /group give <player> <rank> [<seks> <mins> <hours> <days>]"
  GROUP_EDIT_USAGE: "Usage: /group edit (player)"
  RANK_EXISTS: "The rank already exists"
  RANK_DOES_NOT_EXIST: "The rank does not exist"
  SUCESSFULLY_CREATED_GROUP: "The rank was successfully created"
  LIST_RANK: "Ränge:"
  PLAYER_NOT_FOUND: "The player was not found"
  ADDITIONAL_PERMISSIONS: "Additional permissions:"
  UNTIL_PERMANENT: "Until: §cPermanent"
  UNTIL_TEMPORARY: "Until:"
  RANK_SET: "The rank was successfully set"
  GROUP_EDIT_MANUELL: "/group edit <player/rank> (add/remove) <permission>"
  PLAYER_RANK_NOT_FOUND: "Rank/Player not found"
  PLAYER_PERMISSION_ADDED: "Permission added"
  PLAYER_PERMISSION_REMOVED: "Permission removed"
  RANK_PERMISSION_ADDED: "Permission added"
  RANK_PERMISSION_REMOVED: "Permission removed"
  SET_SIGN: "Click a sign to set the rank"
  PLAYER_NEVER_ONLINE: "The player has never been online"
  PLAYER_EDITED_SIGN: "The player has edited the sign"
  STANDARD_RANK_CANNOT_BE_DELETED: "The standard rank cannot be deleted"
  RANK_DELETED: "The rank was successfully deleted"
  NOT_PERMISSION: "You do not have permission to do this"